In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [41]:
from constants import *

In [20]:
from utils import preprocess_genres, save

In [7]:
movies_df = pd.read_csv("ml-20m/movies.csv")
movies_df = preprocess_genres(movies_df)[["movieId", "genres_list"]]
movies_df

       movieId                                        genres_list
0            1  [Adventure, Animation, Children, Comedy, Fantasy]
1            2                     [Adventure, Children, Fantasy]
2            3                                  [Comedy, Romance]
3            4                           [Comedy, Drama, Romance]
4            5                                           [Comedy]
...        ...                                                ...
27273   131254                                           [Comedy]
27274   131256                                           [Comedy]
27275   131258                                        [Adventure]
27276   131260                                               None
27277   131262                       [Adventure, Fantasy, Horror]

[27278 rows x 2 columns]

In [8]:
ratings_df = pd.read_csv("ml-20m/ratings.csv")
ratings_df

          userId  movieId  rating   timestamp
0              1        2     3.5  1112486027
1              1       29     3.5  1112484676
2              1       32     3.5  1112484819
3              1       47     3.5  1112484727
4              1       50     3.5  1112484580
...          ...      ...     ...         ...
20000258  138493    68954     4.5  1258126920
20000259  138493    69526     4.5  1259865108
20000260  138493    69644     3.0  1260209457
20000261  138493    70286     5.0  1258126944
20000262  138493    71619     2.5  1255811136

[20000263 rows x 4 columns]

In [9]:
base_df = ratings_df.merge(movies_df, on="movieId")
del ratings_df
del movies_df

In [10]:
base_df

,userId,movieId,rating,timestamp,genres_list
0,1,2,3.5,1112486027,"[Adventure, Children, Fantasy]"
1,1,29,3.5,1112484676,"[Adventure, Drama, Fantasy, Mystery, Sci-Fi]"
2,1,32,3.5,1112484819,"[Mystery, Sci-Fi, Thriller]"
3,1,47,3.5,1112484727,"[Mystery, Thriller]"
4,1,50,3.5,1112484580,"[Crime, Mystery, Thriller]"
...,...,...,...,...,...
20000258,138493,68954,4.5,1258126920,"[Adventure, Animation, Children, Drama]"
20000259,138493,69526,4.5,1259865108,"[Action, Adventure, Sci-Fi, IMAX]"
20000260,138493,69644,3.0,1260209457,"[Action, Adventure, Animation, Children, Comed..."
20000261,138493,70286,5.0,1258126944,"[Mystery, Sci-Fi, Thriller]"
20000262,138493,71619,2.5,1255811136,[Drama]

In [32]:
BASE_PATH = "datasets/movielens20m"
FULL_PATH = f"{BASE_PATH}/full.csv"
TRAIN_FEATURES_PATH = f"{BASE_PATH}/train_x.csv"
TRAIN_TARGET_PATH = f"{BASE_PATH}/train_y.csv"

TEST_FEATURES_PATH = f"{BASE_PATH}/test_x.csv"
TEST_TARGET_PATH = f"{BASE_PATH}/test_y.csv"

VAL_FEATURES_PATH = f"{BASE_PATH}/val_x.csv"
VAL_TARGET_PATH = f"{BASE_PATH}/val_y.csv"

In [33]:
TRAIN_FEATURES_PATH

'datasets/movielens20m/train_x.csv'

In [17]:
base_df.to_csv(f"${BASE_PATH}/full.csv", index=False)

## Load data

In [23]:
movielens = pd.read_csv("datasets/movielens20m/full.csv")

In [24]:
movielens.columns

Index(['userId', 'movieId', 'rating', 'timestamp', 'genres_list'], dtype='object')

### Prepare data for cross validation


In this section, we divide data as follows:

70%: train set
15%: test set
15%: val set


Hyperparameter tuning will be evaluated on the validation set.

In [25]:
X = movielens.drop(columns=['timestamp', 'genres_list'])

In [26]:
y = movielens[["rating"]]

In [29]:
X_train, X_test_val, y_train, y_test_val = train_test_split(X, y, test_size=0.3, random_state=42)

In [37]:
X_test, y_test, X_val, y_val = train_test_split(X_test_val, y_test_val, test_size=0.5, random_state=42)

### Saving features

In [38]:
save(X_train, TRAIN_FEATURES_PATH)
save(X_test, TEST_FEATURES_PATH)
save(X_val, VAL_FEATURES_PATH)

### Saving targets

In [39]:
save(y_train, TRAIN_TARGET_PATH)

save(y_test, TEST_TARGET_PATH)

save(y_val, VAL_TARGET_PATH)